seed: 0

devices: [0, 1, 2, 3]
workspace: 25000

mini-batch-fit: true
shuffle-in-ram: true

keep-best: true
save-freq: 10000
disp-freq: 1000
disp-first: 10
quiet-translation: true
early-stopping: 10
valid-freq: 10000
valid-mini-batch: 64
valid-metrics:
    - perplexity
    - ce-mean-words
    - bleu
sync-sgd: true
dim-vocabs:
    - 32000
    - 32000

#Unsure about params below

beam-size: 6
normalize: 1
exponential-smoothing: 0.0001

cost-type: ce-mean-words
lr-report: True

transformer-dropout: 0.1
label-smoothing: 0.1
layer-normalization: True

learn-rate: 0.0003
lr-warmup: 16000
lr-decay-inv-sqrt: 16000

optimizer-params:
    - 0.9
    - 0.98
    - 1e-09
