sbatch scripts/evaluate/eval_ensemble.sh ara 1
sbatch scripts/evaluate/eval_ensemble.sh ara 2
sbatch scripts/evaluate/eval_ensemble.sh ara 3
sbatch scripts/evaluate/eval_ensemble.sh ara 4
sbatch scripts/evaluate/eval_ensemble.sh ara 5
sbatch scripts/evaluate/eval_ensemble.sh ara 6
sbatch scripts/evaluate/eval_ensemble.sh ara 7
sbatch scripts/evaluate/eval_ensemble.sh ara 8
sbatch scripts/evaluate/eval_ensemble.sh ara 9
sbatch scripts/evaluate/eval_ensemble.sh ara 10
sbatch scripts/evaluate/eval_ensemble.sh arg 1
sbatch scripts/evaluate/eval_ensemble.sh arg 2
sbatch scripts/evaluate/eval_ensemble.sh arg 3
sbatch scripts/evaluate/eval_ensemble.sh arg 4
sbatch scripts/evaluate/eval_ensemble.sh arg 5
sbatch scripts/evaluate/eval_ensemble.sh arg 6
sbatch scripts/evaluate/eval_ensemble.sh arg 7
sbatch scripts/evaluate/eval_ensemble.sh arg 8
sbatch scripts/evaluate/eval_ensemble.sh arg 9
sbatch scripts/evaluate/eval_ensemble.sh arg 10
sbatch scripts/evaluate/eval_ensemble.sh ast 1
sbatch scripts/evaluate/eval_ensemble.sh ast 2
sbatch scripts/evaluate/eval_ensemble.sh ast 3
sbatch scripts/evaluate/eval_ensemble.sh ast 4
sbatch scripts/evaluate/eval_ensemble.sh ast 5
sbatch scripts/evaluate/eval_ensemble.sh ast 6
sbatch scripts/evaluate/eval_ensemble.sh ast 7
sbatch scripts/evaluate/eval_ensemble.sh ast 8
sbatch scripts/evaluate/eval_ensemble.sh ast 9
sbatch scripts/evaluate/eval_ensemble.sh ast 10