####
# Example of a production config
# Change language pair, experiment name, datasets and other settings if needed
# Training low resource languages might require more tuning of pipeline/training/configs
###

experiment:
  dirname: emnlp
  name: lowres-spain
  langpairs:
    - es-ar
    - es-an
    - es-as

  parallel-max-sentences: 10000000
  split-length: 1000000
  
  one2many-student: True
  
  best-model: bleu
  spm-sample-size: 1000000
  

datasets:
  train:
    - tc_Tatoeba-Challenge-v2023-09-26
  devtest:
    - flores_dev
  test:
    - flores_devtest
